# Generated by Django 5.2.4 on 2025-08-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkconnection',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='databasemetrics',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_metrics', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='alert',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.system'),
        ),
        migrations.AddIndex(
            model_name='networkconnection',
            index=models.Index(fields=['system', 'timestamp'], name='network_con_system__5a51b2_idx'),
        ),
        migrations.AddIndex(
            model_name='networkconnection',
            index=models.Index(fields=['protocol', 'status'], name='network_con_protoco_625d38_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['system', 'timestamp'], name='log_entries_system__ef8e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['level', 'timestamp'], name='log_entries_level_84d8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['source', 'timestamp'], name='log_entries_source_0b54ab_idx'),
        ),
        migrations.AddIndex(
            model_name='databasemetrics',
            index=models.Index(fields=['system', 'timestamp'], name='database_me_system__548c77_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['system', 'status'], name='alerts_system__d712b9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='alerts_severit_ae6d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alerts_created_965da5_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['system', 'timestamp'], name='system_metr_system__4804bd_idx'),
        ),
    ]
