# Generated by Django 4.2.23 on 2025-07-20 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdfimport', '0002_document_file_hash_alter_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
