# Generated by Django 5.2.7 on 2025-10-25 11:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0009_update_embedding_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
