# Generated by Django 5.2.7 on 2025-10-27 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0011_documentfile_metadata_documentfile_source_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": [
                    "uploaded_file",
                    "document_file",
                    "page_number",
                    "chunk_index",
                ]
            },
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="ai_assistant.documentfile",
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("doc", "Word Document"),
                    ("docx", "Word Document"),
                    ("xls", "Excel Spreadsheet"),
                    ("xlsx", "Excel Spreadsheet"),
                    ("ppt", "PowerPoint Presentation"),
                    ("pptx", "PowerPoint Presentation"),
                    ("txt", "Text Document"),
                    ("rtf", "Rich Text Document"),
                    ("SSB_KPR", "SSB/KPR File"),
                    ("ssb", "SSB Entry"),
                    ("github", "GitHub Repository"),
                    ("forum", "Forum Post"),
                    ("html", "HTML Content"),
                    ("url", "Web URL"),
                    ("video", "Video Transcript"),
                    ("image", "Image with OCR"),
                ],
                default="pdf",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "txt",
                            "rtf",
                            "mhtml",
                            "html",
                        ]
                    )
                ],
            ),
        ),
    ]
