# Generated by Django 5.2.7 on 2025-10-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0015_add_duplicate_detection_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="uploadedfile",
            new_name="ai_assistan_process_2eb398_idx",
            old_name="ai_uploadedfile_processing_status_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadedfile",
            new_name="ai_assistan_metadat_30383f_idx",
            old_name="ai_uploadedfile_completion_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadedfile",
            new_name="ai_assistan_filenam_66a406_idx",
            old_name="ai_uploadedfile_filename_size_idx",
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_size",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="filename",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
