# Generated by Django 5.2.7 on 2025-10-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0016_add_filename_size_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_files",
                to="ai_assistant.uploadedfile",
            ),
        ),
    ]
