# Generated by Django 5.2.7 on 2025-10-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0017_add_uploaded_file_to_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="is_truncated",
            field=models.BooleanField(
                default=False,
                help_text="True if document was truncated due to size limits",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="processing_coverage",
            field=models.FloatField(
                default=100.0,
                help_text="Percentage of document that was processed (0-100)",
            ),
        ),
    ]
