# Generated by Django 5.2.7 on 2025-11-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0020_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="channel",
            field=models.CharField(
                choices=[
                    ("chat", "ChatAssistant"),
                    ("rag_basic", "Basic RAG"),
                    ("rag", "RAG"),
                    ("rag_comprehensive", "Comprehensive RAG"),
                    ("rag_graph", "Graph RAG"),
                    ("troubleshooting", "Troubleshooting"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
