# Generated by Django 5.2.4 on 2025-12-25 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0021_alter_chatmessage_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("file", "File Upload"),
                            ("folder", "Folder Scan"),
                            ("webpage", "Webpage Download"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(
                        help_text="File path, folder path, or URL", max_length=1000
                    ),
                ),
                (
                    "source_files",
                    models.JSONField(
                        default=list, help_text="List of files to process"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=5,
                        help_text="Priority 1-10, higher = more important",
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("completed_items", models.IntegerField(default=0)),
                ("failed_items", models.IntegerField(default=0)),
                (
                    "last_processed_file_index",
                    models.IntegerField(default=0, help_text="Checkpoint for resume"),
                ),
                ("paused", models.BooleanField(db_index=True, default=False)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="User-provided metadata"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Job-level error message", null=True
                    ),
                ),
                (
                    "file_errors",
                    models.JSONField(
                        blank=True, default=dict, help_text="Per-file error tracking"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority", "created_at"],
                        name="ai_assistan_status_43f74f_idx",
                    ),
                    models.Index(
                        fields=["job_type", "status"],
                        name="ai_assistan_job_typ_f61f95_idx",
                    ),
                    models.Index(
                        fields=["paused", "status"],
                        name="ai_assistan_paused_97c0de_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="ai_assistan_created_f23a05_idx",
                    ),
                ],
            },
        ),
    ]
