# Generated by Django 5.2.4 on 2026-01-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0022_add_upload_job"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]
