services:
  # PostgreSQL Database
  db:
    image: pgvector/pgvector:pg16
    container_name: onelab_db
    environment:
      - POSTGRES_DB=onelab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - onelab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    container_name: onelab_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - onelab_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application
  web:
    image: onelab-backend:latest
    container_name: onelab_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout 600 onelab.wsgi:application"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - ./media:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-this-in-production
      - DB_NAME=onelab
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - EMBEDDING_MODE=lightweight
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen2.5:latest
      - EMBEDDING_MODEL=bge-m3
      - WEB_WORKERS=2
      - WEB_TIMEOUT=600
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - onelab_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Soft cap CPU usage for web
    cpus: "1.50"

  # Celery Worker
  celery:
    image: onelab-backend:latest
    container_name: onelab_celery
    command: >
      sh -c "celery -A onelab worker --loglevel=info --concurrency=2"
    volumes:
      - .:/code
      - ./media:/code/media
      - ./logs:/code/logs
    env_file:
      - .env
    environment:
      # Database Settings - FORCED for Docker
      - DB_NAME=onelab
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      # Application Settings
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-this-in-production
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Limit math libs thread counts
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - FAISS_NUM_THREADS=1
      - CELERY_CONCURRENCY=${CELERY_CONCURRENCY:-2}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - onelab_network
    restart: unless-stopped
    cpus: "1.00"

  # Celery Beat (Scheduler)
  celery-beat:
    image: onelab-backend:latest
    container_name: onelab_celery_beat
    command: >
      sh -c "celery -A onelab beat --loglevel=info"
    volumes:
      - .:/code
      - ./media:/code/media
      - ./logs:/code/logs
    env_file:
      - .env
    environment:
      # Database Settings - FORCED for Docker
      - DB_NAME=onelab
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      # Application Settings
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-this-in-production
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - FAISS_NUM_THREADS=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - onelab_network
    restart: unless-stopped
    cpus: "0.50"

  # Celery Flower (Monitoring)
  flower:
    image: onelab-backend:latest
    container_name: onelab_flower
    command: >
      sh -c "celery -A onelab flower --port=5555"
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      # Database Settings - FORCED for Docker
      - DB_NAME=onelab
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      # Application Settings
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-this-in-production
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - celery
    networks:
      - onelab_network
    restart: unless-stopped
    volumes:
      - .:/code



volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local


networks:
  onelab_network:
    driver: bridge 