# Generated by Django 5.2.7 on 2025-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0010_alter_documentchunk_embedding_delete_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("doc", "Word Document"),
                    ("docx", "Word Document"),
                    ("xls", "Excel Spreadsheet"),
                    ("xlsx", "Excel Spreadsheet"),
                    ("ppt", "PowerPoint Presentation"),
                    ("pptx", "PowerPoint Presentation"),
                    ("txt", "Text Document"),
                    ("rtf", "Rich Text Document"),
                    ("ssb", "SSB Entry"),
                    ("github", "GitHub Repository"),
                    ("forum", "Forum Post"),
                    ("html", "HTML Content"),
                    ("url", "Web URL"),
                    ("video", "Video Transcript"),
                    ("image", "Image with OCR"),
                ],
                default="pdf",
                max_length=10,
            ),
        ),
    ]
