# Generated by Django 5.2.7 on 2025-10-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0012_add_document_file_to_chunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpPortalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cds", "OpenLab CDS"),
                            ("ecm", "OpenLab Server/ECM XT"),
                            ("shared", "Shared Services"),
                            ("services", "Test Services"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("document_type", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("chunk_count", models.IntegerField(default=0)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.uploadedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "filename"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="ai_assistan_status_433f10_idx"
                    ),
                    models.Index(
                        fields=["category"], name="ai_assistan_categor_690172_idx"
                    ),
                    models.Index(
                        fields=["file_hash"], name="ai_assistan_file_ha_b3fc12_idx"
                    ),
                ],
            },
        ),
    ]
