# Generated by Django 5.2.7 on 2025-10-29 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0018_add_truncation_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=512, unique=True)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetching", "Fetching Content"),
                            ("metadata_extracting", "Extracting Metadata"),
                            ("chunking", "Generating Chunks"),
                            ("embedding", "Creating Embeddings"),
                            ("ready", "Ready for Search"),
                            ("failed", "Processing Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata_extracted", models.BooleanField(default=False)),
                ("chunks_created", models.BooleanField(default=False)),
                ("embeddings_created", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("chunk_count", models.IntegerField(default=0)),
                ("embedding_count", models.IntegerField(default=0)),
                ("page_count", models.IntegerField(default=0)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("next_refresh_at", models.DateTimeField(blank=True, null=True)),
                ("auto_refresh", models.BooleanField(default=True)),
                ("refresh_interval_days", models.IntegerField(default=7)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_assistant.uploadedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["processing_status"],
                        name="ai_assistan_process_3c43c7_idx",
                    ),
                    models.Index(
                        fields=["domain"], name="ai_assistan_domain_5e37b4_idx"
                    ),
                    models.Index(fields=["url"], name="ai_assistan_url_590d49_idx"),
                    models.Index(
                        fields=["created_at"], name="ai_assistan_created_fb5249_idx"
                    ),
                ],
            },
        ),
    ]
