# Generated by Django 5.2.7 on 2025-10-30 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0019_add_website_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("chat", "ChatAssistant"),
                            ("rag_basic", "Basic RAG"),
                            ("rag", "RAG"),
                            ("rag_comprehensive", "Comprehensive RAG"),
                            ("troubleshooting", "Troubleshooting"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("thread_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_assistan_user_id_2c29eb_idx",
                    ),
                    models.Index(
                        fields=["user", "channel", "created_at"],
                        name="ai_assistan_user_id_f59730_idx",
                    ),
                    models.Index(
                        fields=["thread_id", "created_at"],
                        name="ai_assistan_thread__7fcd86_idx",
                    ),
                ],
            },
        ),
    ]
