# Generated by Django 5.2.4 on 2025-08-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='systems',
            field=models.ManyToManyField(related_name='maintenance_tasks', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.maintenancetask'),
        ),
        migrations.AddField(
            model_name='performancebaseline',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_baselines', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_queries', to='monitoring.system'),
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['system', 'started_at'], name='database_ba_system__c41040_idx'),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['status', 'started_at'], name='database_ba_status_55d1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['status', 'scheduled_date'], name='maintenance_status_a04449_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['priority', 'status'], name='maintenance_priorit_5ad31e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['assigned_to', 'status'], name='maintenance_assigne_e1fbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='sqlquery',
            index=models.Index(fields=['system', 'timestamp'], name='sql_queries_system__5caef5_idx'),
        ),
        migrations.AddIndex(
            model_name='sqlquery',
            index=models.Index(fields=['query_type', 'timestamp'], name='sql_queries_query_t_2b5f74_idx'),
        ),
        migrations.AddIndex(
            model_name='sqlquery',
            index=models.Index(fields=['execution_time'], name='sql_queries_executi_ec7a5f_idx'),
        ),
    ]
