"""
Management command to set up automated monitoring via cron jobs.

Usage:
    python manage.py setup_monitoring
    python manage.py setup_monitoring --show-only
"""

from django.core.management.base import BaseCommand
import os
import stat

logger = None


class Command(BaseCommand):
    help = 'Set up automated monitoring via cron jobs'

    def add_arguments(self, parser):
        parser.add_argument(
            '--show-only',
            action='store_true',
            help='Show cron job entries without installing them'
        )

    def handle(self, *args, **options):
        show_only = options.get('show_only', False)
        
        self.stdout.write(f'\n{"="*60}')
        self.stdout.write('AUTOMATED MONITORING SETUP')
        self.stdout.write(f'{"="*60}\n')
        
        # Get project root and manage.py path
        import django
        django_path = os.path.dirname(os.path.dirname(os.path.dirname(django.__file__)))
        manage_py_path = os.path.join(django_path, 'manage.py')
        
        # Use actual manage.py path
        import sys
        manage_py_path = sys.argv[0] if sys.argv[0].endswith('manage.py') else 'python manage.py'
        project_dir = os.getcwd()
        
        cron_jobs = [
            {
                'schedule': '*/5 * * * *',  # Every 5 minutes
                'command': f'cd {project_dir} && {manage_py_path} validate_processing --recent-hours 1',
                'description': 'Validate processing every 5 minutes'
            },
            {
                'schedule': '*/15 * * * *',  # Every 15 minutes
                'command': f'cd {project_dir} && {manage_py_path} check_logs --hours 1',
                'description': 'Check logs for errors every 15 minutes'
            },
            {
                'schedule': '0 * * * *',  # Every hour
                'command': f'cd {project_dir} && {manage_py_path} monitor_performance --hours 24',
                'description': 'Monitor performance every hour'
            },
            {
                'schedule': '0 0 * * *',  # Daily at midnight
                'command': f'cd {project_dir} && {manage_py_path} validate_processing --check-embeddings --check-chunks --recent-hours 168',
                'description': 'Full validation daily'
            },
        ]
        
        self.stdout.write('Cron Jobs to Install:\n')
        for i, job in enumerate(cron_jobs, 1):
            self.stdout.write(f'{i}. {job["description"]}')
            self.stdout.write(f'   Schedule: {job["schedule"]}')
            self.stdout.write(f'   Command: {job["command"]}\n')
        
        if show_only:
            self.stdout.write('\n(Show-only mode - not installing cron jobs)')
            self.stdout.write('\nTo install, run without --show-only flag')
            return
        
        # Generate crontab entry
        crontab_entries = []
        crontab_entries.append('# Automated monitoring for AI Assistant file processing')
        crontab_entries.append('# Generated by setup_monitoring management command')
        crontab_entries.append('')
        
        for job in cron_jobs:
            crontab_entries.append(f'{job["schedule"]} {job["command"]} >> /tmp/ai_assistant_monitoring.log 2>&1')
        
        crontab_content = '\n'.join(crontab_entries)
        
        # Save to file
        cron_file = os.path.join(project_dir, 'ai_assistant_monitoring.cron')
        with open(cron_file, 'w') as f:
            f.write(crontab_content)
        
        self.stdout.write(f'\nCron file created: {cron_file}')
        self.stdout.write('\nTo install, run:')
        self.stdout.write(f'  crontab {cron_file}')
        self.stdout.write('\nTo view current crontab:')
        self.stdout.write('  crontab -l')
        self.stdout.write('\nTo remove:')
        self.stdout.write('  crontab -r')
        self.stdout.write(f'\n{"="*60}\n')

