services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    platform: linux/arm64
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "${POSTGRES_PORT_EXPOSED:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_django_app
    container_name: django_web
    platform: linux/arm64
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - ./all-MiniLM-L6-v2_local_copy:/model/all-MiniLM-L6-v2
    ports:
      - "${WEB_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - OLLAMA_API_BASE_URL=http://ollama:11434
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    platform: linux/arm64
    ports:
      - "${OLLAMA_PORT:-11435}:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '2.0'
        reservations:
          memory: 3G
          cpus: '1.0'

  # Add nginx for production deployment
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    platform: linux/arm64
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

volumes:
  postgres_data:
  ollama_data:
  static_volume:
  media_volume: 