# Generated by Django 5.2.4 on 2025-08-17 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_systemmetrics_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("sysmon", "SysMon Agent"),
                            ("appmon", "AppMon Agent"),
                            ("windows", "Windows Agent"),
                            ("manual", "Manual Entry"),
                        ],
                        default="appmon",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="monitoring.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "applications",
                "unique_together": {("name", "system")},
            },
        ),
        migrations.CreateModel(
            name="ApplicationAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("source_name", models.CharField(blank=True, max_length=100)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("pattern_matched", models.CharField(blank=True, max_length=100)),
                ("context_lines", models.JSONField(blank=True, default=list)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.application",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_app_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Alert",
                "verbose_name_plural": "Application Alerts",
                "db_table": "application_alerts",
                "indexes": [
                    models.Index(
                        fields=["application", "status"],
                        name="application_applica_5d68e7_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="application_severit_fb9e1d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="application_created_f0dff4_idx"
                    ),
                    models.Index(
                        fields=["fingerprint"], name="application_fingerp_097442_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApplicationMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("files_monitored", models.IntegerField(default=0)),
                ("total_log_size_mb", models.FloatField(default=0.0)),
                ("largest_file_mb", models.FloatField(default=0.0)),
                ("total_alerts_sent", models.IntegerField(default=0)),
                ("unique_alerts_sent", models.IntegerField(default=0)),
                ("duplicate_alerts_suppressed", models.IntegerField(default=0)),
                ("scan_duration_ms", models.FloatField(default=0.0)),
                ("scan_frequency_per_minute", models.FloatField(default=0.0)),
                ("active_sources", models.IntegerField(default=0)),
                ("total_patterns", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("last_error_time", models.DateTimeField(blank=True, null=True)),
                ("alert_cache_size", models.IntegerField(default=0)),
                ("cache_hit_rate", models.FloatField(default=0.0)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="monitoring.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Metric",
                "verbose_name_plural": "Application Metrics",
                "db_table": "application_metrics",
                "indexes": [
                    models.Index(
                        fields=["application", "timestamp"],
                        name="application_applica_25d5d9_idx",
                    )
                ],
            },
        ),
    ]
