# Generated by Django 5.2.7 on 2025-11-01 13:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or class", max_length=50
                    ),
                ),
                ("sort_order", models.IntegerField(db_index=True, default=0)),
                (
                    "is_public_visible",
                    models.BooleanField(
                        default=True, help_text="Visible to non-logged-in users"
                    ),
                ),
                (
                    "allow_public_post",
                    models.BooleanField(
                        default=False, help_text="Allow non-logged-in users to post"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Forum Category",
                "verbose_name_plural": "Forum Categories",
                "db_table": "forum_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ForumTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", help_text="Hex color code", max_length=7
                    ),
                ),
                ("usage_count", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Forum Tag",
                "verbose_name_plural": "Forum Tags",
                "db_table": "forum_tags",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("locked", "Locked"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "is_public_visible",
                    models.BooleanField(
                        default=False, help_text="Visible to non-logged-in users"
                    ),
                ),
                (
                    "allow_public_reply",
                    models.BooleanField(
                        default=False, help_text="Allow non-logged-in users to reply"
                    ),
                ),
                ("is_pinned", models.BooleanField(db_index=True, default=False)),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, help_text="精华帖"
                    ),
                ),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(db_index=True, default=0)),
                ("like_count", models.IntegerField(db_index=True, default=0)),
                ("reply_count", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_reply_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="forum.forumcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Post",
                "verbose_name_plural": "Forum Posts",
                "db_table": "forum_posts",
                "ordering": ["-is_pinned", "-last_reply_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_public_visible",
                    models.BooleanField(
                        default=False, help_text="Visible to non-logged-in users"
                    ),
                ),
                ("like_count", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_reply",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nested reply",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_replies",
                        to="forum.forumreply",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "quoted_reply",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quoted reply",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quoted_in_replies",
                        to="forum.forumreply",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Reply",
                "verbose_name_plural": "Forum Replies",
                "db_table": "forum_replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_reply", "New Reply"),
                            ("mention", "Mention"),
                            ("like", "Like"),
                            ("quote", "Quote"),
                            ("post_locked", "Post Locked"),
                            ("post_deleted", "Post Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the notification",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="forum.forumreply",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Notification",
                "verbose_name_plural": "Forum Notifications",
                "db_table": "forum_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "mentioned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentioned_others",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="forum.forumreply",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Mention",
                "verbose_name_plural": "Forum Mentions",
                "db_table": "forum_mentions",
            },
        ),
        migrations.CreateModel(
            name="ForumLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like_type",
                    models.CharField(
                        choices=[("post", "Post"), ("reply", "Reply")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="forum.forumreply",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Like",
                "verbose_name_plural": "Forum Likes",
                "db_table": "forum_likes",
            },
        ),
        migrations.CreateModel(
            name="ForumAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="forum/attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "txt",
                                    "rtf",
                                    "zip",
                                    "rar",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "avi",
                                    "mov",
                                ]
                            )
                        ],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="forum.forumreply",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forum Attachment",
                "verbose_name_plural": "Forum Attachments",
                "db_table": "forum_attachments",
            },
        ),
        migrations.CreateModel(
            name="ForumPostTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_tags",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_tags",
                        to="forum.forumtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Tag",
                "verbose_name_plural": "Post Tags",
                "db_table": "forum_post_tags",
            },
        ),
        migrations.AddField(
            model_name="forumpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                through="forum.ForumPostTag",
                to="forum.forumtag",
            ),
        ),
        migrations.AddIndex(
            model_name="forumreply",
            index=models.Index(
                fields=["post", "created_at"], name="forum_repli_post_id_a18123_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumreply",
            index=models.Index(
                fields=["parent_reply", "created_at"],
                name="forum_repli_parent__6377b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumnotification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="forum_notif_recipie_d49104_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumnotification",
            index=models.Index(
                fields=["notification_type"], name="forum_notif_notific_80f281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forummention",
            index=models.Index(
                fields=["mentioned_user", "is_read", "-created_at"],
                name="forum_menti_mention_0ba1a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forummention",
            index=models.Index(fields=["post"], name="forum_menti_post_id_92831b_idx"),
        ),
        migrations.AddIndex(
            model_name="forummention",
            index=models.Index(fields=["reply"], name="forum_menti_reply_i_19bfd7_idx"),
        ),
        migrations.AddIndex(
            model_name="forumlike",
            index=models.Index(
                fields=["like_type", "created_at"],
                name="forum_likes_like_ty_885c80_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forumlike",
            unique_together={("user", "post"), ("user", "reply")},
        ),
        migrations.AddIndex(
            model_name="forumattachment",
            index=models.Index(fields=["post"], name="forum_attac_post_id_ed9eba_idx"),
        ),
        migrations.AddIndex(
            model_name="forumattachment",
            index=models.Index(fields=["reply"], name="forum_attac_reply_i_d141a7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="forumposttag",
            unique_together={("post", "tag")},
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["status", "is_pinned", "-created_at"],
                name="forum_posts_status_c2f4c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["category", "status"], name="forum_posts_categor_b3122a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["is_featured", "-created_at"],
                name="forum_posts_is_feat_6c8b5d_idx",
            ),
        ),
    ]
